//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesAccess.wsEstacionamientoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WsEstacionamiento")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsEstacionamientoService.IEstacionamientoService")]
    public interface IEstacionamientoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetData", ReplyAction="http://tempuri.org/IEstacionamientoService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetData", ReplyAction="http://tempuri.org/IEstacionamientoService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEstacionamientoService/GetDataUsingDataContractResponse")]
        ServicesAccess.wsEstacionamientoService.CompositeType GetDataUsingDataContract(ServicesAccess.wsEstacionamientoService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IEstacionamientoService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServicesAccess.wsEstacionamientoService.CompositeType> GetDataUsingDataContractAsync(ServicesAccess.wsEstacionamientoService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetListadoAutos", ReplyAction="http://tempuri.org/IEstacionamientoService/GetListadoAutosResponse")]
        string GetListadoAutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetListadoAutos", ReplyAction="http://tempuri.org/IEstacionamientoService/GetListadoAutosResponse")]
        System.Threading.Tasks.Task<string> GetListadoAutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetListadoEmpleados", ReplyAction="http://tempuri.org/IEstacionamientoService/GetListadoEmpleadosResponse")]
        string GetListadoEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstacionamientoService/GetListadoEmpleados", ReplyAction="http://tempuri.org/IEstacionamientoService/GetListadoEmpleadosResponse")]
        System.Threading.Tasks.Task<string> GetListadoEmpleadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstacionamientoServiceChannel : ServicesAccess.wsEstacionamientoService.IEstacionamientoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstacionamientoServiceClient : System.ServiceModel.ClientBase<ServicesAccess.wsEstacionamientoService.IEstacionamientoService>, ServicesAccess.wsEstacionamientoService.IEstacionamientoService {
        
        public EstacionamientoServiceClient() {
        }
        
        public EstacionamientoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstacionamientoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstacionamientoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstacionamientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServicesAccess.wsEstacionamientoService.CompositeType GetDataUsingDataContract(ServicesAccess.wsEstacionamientoService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServicesAccess.wsEstacionamientoService.CompositeType> GetDataUsingDataContractAsync(ServicesAccess.wsEstacionamientoService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetListadoAutos() {
            return base.Channel.GetListadoAutos();
        }
        
        public System.Threading.Tasks.Task<string> GetListadoAutosAsync() {
            return base.Channel.GetListadoAutosAsync();
        }
        
        public string GetListadoEmpleados() {
            return base.Channel.GetListadoEmpleados();
        }
        
        public System.Threading.Tasks.Task<string> GetListadoEmpleadosAsync() {
            return base.Channel.GetListadoEmpleadosAsync();
        }
    }
}
